 class Sam
{
 public static void main(String[]arg)
{
char a1='A';
char b1='B';
char c1='C';
char d1='D';
char e1='E';
char f1='F';
char g1='G';
char h1='H';
char i1='I';
char j1='J';
char k1='K';
char l1='L';
char m1='M';
char n1='N';
char o1='O';
char p1='P';
char q1='Q';
char r1='R';
char s1='S';
char t1='T';
char u1='U';
char v1='V';
char w1='W';
char x1='X';
char y1='Y';
char z1='Z';
int num1=a1;
int num2=b1;
int num3=c1;
int num4=d1;
int num5=e1;
int num6=f1;
int num7=g1;
int num8=h1;
int num9=i1;
int num10=j1;
int num11=k1;
int num12=l1;
int num13=m1;
int num14=n1;
int num15=o1;
int num16=p1;
int num17=q1;
int num18=r1;
int num19=s1;
int num20=t1;
int num21=u1;
int num22=v1;
int num23=w1;
int num24=x1;
int num25=y1;
int num26=z1;
int z=a1+32;
int y=b1+32;
int x=c1+32;
int w=d1+32;
int u=e1+32;
int v=f1+32;
int t=g1+32;
int s=h1+32;
int r=i1+32;
int q=j1+32;
int p=k1+32;
int o=l1+32;
int n=m1+32;
int m=n1+32;
int l=o1+32;
int k=p1+32;
int j=q1+32;
int i=r1+32;
int h=s1+32;
int g=t1+32;
int f=u1+32;
int e=v1+32;
int d=w1+32;
int c=x1+32;
int b=y1+32;
int a=z1+32;
char nu1=(char)z;
char nu2=(char)y;
char nu3=(char)x;
char nu4=(char)w;
char nu5=(char)u;
char nu6=(char)v;
char nu7=(char)t;
char nu8=(char)s;
char nu9=(char)r;
char nu10=(char)q;
char nu11=(char)p;
char nu12=(char)o;
char nu13=(char)n;
char nu14=(char)m;
char nu15=(char)l;
char nu16=(char)k;
char nu17=(char)j;
char nu18=(char)i;
char nu19=(char)h;
char nu20=(char)g;
char nu21=(char)f;
char nu22=(char)e;
char nu23=(char)d;
char nu24=(char)c;
char nu25=(char)b;
char nu26=(char)a;
System.out.println(z);
System.out.println(y);
System.out.println(x);
System.out.println(w);
System.out.println(v);
System.out.println(u);
System.out.println(t);
System.out.println(s);
System.out.println(r);
System.out.println(q);
System.out.println(p);
System.out.println(o);
System.out.println(n);
System.out.println(m);
System.out.println(l);
System.out.println(k);
System.out.println(j);
System.out.println(i);
System.out.println(h);
System.out.println(g);
System.out.println(f);
System.out.println(e);
System.out.println(d);
System.out.println(c);
System.out.println(b);
System.out.println(a);
 System.out.println(nu1);
 System.out.println(nu2);
 System.out.println(nu3);
 System.out.println(nu4);
 System.out.println(nu5);
 System.out.println(nu6);
 System.out.println(nu7);
 System.out.println(nu8);
System.out.println(nu9);
 System.out.println(nu10);
 System.out.println(nu11);
 System.out.println(nu12);
System.out.println(nu13);
 System.out.println(nu14);
System.out.println(nu15);
 System.out.println(nu16);
System.out.println(nu17);
 System.out.println(nu18);
System.out.println(nu19);
 System.out.println(nu20);
System.out.println(nu21);
 System.out.println(nu22);
System.out.println(nu23);
 System.out.println(nu24);
System.out.println(nu25);
 System.out.println(nu26);
}
}